services:
  jupyter:
    image: jupyter-r:latest # jupyter:latest for Jupyter without R
    ports:
      - "8888:8888"
    volumes:
      - type: "bind"
        source: "."
        target: "/home/workspace"
    environment:
      - JUPYTER_TOKEN=jupyter
    command: >
      bash -c "Rscript /init_scripts/r_jupyter_kernel.r && 
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
      
      # Only jupyter lab command for Jupyter without R