services:
  rstudio:
    image: rstudio:latest
    ports:
      - "8787:8787"
    volumes:
      - type: "bind"
        source: "."
        target: "/home/rstudio"
    environment:
      - DEFAULT_USER=rstudio
      - PASSWORD=rstudio
    command: /init